# Generated by Django 5.0.6 on 2024-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.IntegerField(default=1),
        ),
    ]
