# Generated by Django 5.0.6 on 2024-07-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_notification_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('MESSAGE', 'Message')], max_length=20),
        ),
    ]
