# Generated by Django 5.0.6 on 2024-08-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('SALES_MANAGER', 'Sales Manager'), ('ADMIN', 'Admin'), ('DELIVERY TEAM', 'Delivery Team')], default='CUSTOMER', max_length=20),
        ),
    ]
